"""Signal 1 — LLM classification via Groq (the *semantic* signal).

Asks a Groq-hosted model whether a piece of text was substantially generated by
AI and passed off as original human work, and returns an AI-likelihood in
[0, 1]. This captures holistic semantic/stylistic coherence — the thing pure
heuristics miss. Its blind spot (an AI judging AI: uncalibrated, non-deterministic,
prone to over-flagging formal/non-native writing) is why it is paired with the
deterministic stylometry signal. See planning.md "Detection signals".

The function is dependency-injectable: pass a ``client`` to use a stub in tests
or a pre-built Groq client in production. With no client and no API key it
degrades gracefully to a neutral 0.5 ("can't tell") rather than crashing — an
unavailable signal must never become a confident accusation.
"""

from __future__ import annotations

import json
import os
from typing import Any, Optional

from provenance.config import GROQ_MODEL

SYSTEM_PROMPT = (
    "You are a forensic text analyst. Assess whether the user's text was "
    "SUBSTANTIALLY generated by an AI language model and passed off as a "
    "person's original creative work. Light AI polishing, grammar checkers, and "
    "spell-check do NOT count as AI generation. Be cautious about accusing real "
    "people: a false accusation of a human writer is worse than missing an AI. "
    "Respond with ONLY a JSON object of the exact form: "
    '{"verdict": "human" | "ai", "ai_likelihood": <number 0..1>, '
    '"reasoning": "<one short sentence>"}. '
    "ai_likelihood is your probability that the text was substantially "
    "AI-generated (0 = certainly a human, 1 = certainly AI)."
)


def _neutral(reason: str, error: Optional[str] = None) -> dict[str, Any]:
    """A safe fallback used whenever the LLM signal cannot produce a result."""
    return {
        "verdict": "uncertain",
        "ai_likelihood": 0.5,
        "reasoning": reason,
        "error": error,
    }


def _coerce(data: dict[str, Any]) -> dict[str, Any]:
    """Validate/normalize a parsed model response into our contract."""
    raw = data.get("ai_likelihood")
    try:
        likelihood = float(raw)
    except (TypeError, ValueError):
        # No usable number — derive a soft value from the verdict instead.
        verdict = str(data.get("verdict", "")).lower()
        likelihood = 0.8 if verdict == "ai" else 0.2 if verdict == "human" else 0.5
    likelihood = max(0.0, min(1.0, likelihood))

    verdict = str(data.get("verdict", "")).lower()
    if verdict not in ("human", "ai"):
        verdict = "ai" if likelihood >= 0.5 else "human"

    reasoning = str(data.get("reasoning") or "No reasoning provided.")
    return {
        "verdict": verdict,
        "ai_likelihood": likelihood,
        "reasoning": reasoning,
        "error": None,
    }


def _build_client() -> Optional[Any]:
    """Construct a real Groq client from the environment, or None if no key."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None
    from groq import Groq  # imported lazily so tests need not have it configured

    return Groq(api_key=api_key)


def llm_signal(text: str, *, client: Optional[Any] = None) -> dict[str, Any]:
    """Classify ``text`` with the LLM signal.

    Returns a dict ``{verdict, ai_likelihood, reasoning, error}``. ``error`` is
    ``None`` on success or a short error tag on graceful degradation.
    """
    if client is None:
        client = _build_client()
    if client is None:
        return _neutral(
            "LLM signal unavailable (no GROQ_API_KEY); defaulting to uncertain.",
            error="no_api_key",
        )

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,  # low temp for stability across identical inputs
            response_format={"type": "json_object"},
        )
        content = response.choices[0].message.content
        data = json.loads(content)
    except json.JSONDecodeError:
        return _neutral(
            "LLM returned malformed JSON; defaulting to uncertain.",
            error="malformed_json",
        )
    except Exception as exc:  # network/auth/rate-limit/etc. — never crash /submit
        return _neutral(
            f"LLM signal error ({type(exc).__name__}); defaulting to uncertain.",
            error=type(exc).__name__,
        )

    if not isinstance(data, dict):
        return _neutral(
            "LLM returned non-object JSON; defaulting to uncertain.",
            error="bad_shape",
        )
    return _coerce(data)
